server:
  port: 8001  # 网关端口

spring:
  application:
    name: api-gateway # 服务名称
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos注册中心地址

    gateway:
      routes: # 网关路由配置
        - id: order-service # 路由id，自定义，只要唯一就可以，一般是服务名称
          # uri: http://127.0.0.1:8801  # 路由的目标地址，http就是固定地址，一般不适用
          uri: lb://order-service # 路由的目标地址，lb就是负载均衡（所以新版本要加负载均衡依赖），后面跟服务名称
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件，符合就路由到上面的uri
            - Path=/orders/**  # 这个按按照路径匹配，只要是以 /user/ 开头就符合要求
            #- After=2031-04-13T15:14:47.433+08:00[Asia/Shanghai] # 要求时间在这个之后，并且路径是/user/开头
            - Before=2023-12-02T15:14:47.433+08:00[Asia/Shanghai]  # 要求时间在这个之前，并且路径是/user/开头

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

logging:
  level:
    com.cloud.gateway: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS