server:
  port: 8101

spring:
  application:
    name: order-service
  # 数据源
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/cloud_order?useSSL=true
      username: root
      password: 1234
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848 # nacos注册中心地址
      discovery:
        cluster-name: HZ  # 配置集群名称，也就是机房位置，例如：HZ，杭州
        # namespace: ff0fc139-a5a3-461f-8b36-d0fc1f67a264  # 配置命名空间：dev环境
        # ephemeral: false  # 把实例设置成非临时实例

#需改负载均衡规则：优先访问同集群的实例
user-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule # 负载均衡规则

# mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      table-prefix: tb_
      id-type: auto
  type-aliases-package: com.cloud.order.pojo
  mapper-locations: classpath:mapper/*.xml

# 日志
logging:
  level:
    com.cloud.order: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS


#feign:
#  client:
#    config:
#      default:
#        loggerLevel: FULL
#feign:
#  httpclient:
#    enabled: true # 打开支持HttpClient的开关
#    max-connections: 200 # 最大连接数
#    max-connections-per-route: 50 # 单个请求路径的最大连接数